# Generated by Django 3.2.6 on 2022-01-18 20:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigIntegerField(db_column='_id', primary_key=True, serialize=False)),
                ('tweet_id', models.TextField(db_column='tweet_id')),
                ('name', models.TextField(db_column='name')),
                ('username', models.TextField(db_column='username')),
                ('postdate', models.TextField(db_column='postdate')),
                ('timestamp', models.BigIntegerField(blank=True, db_column='timestamp', null=True)),
                ('date', models.DateTimeField(db_column='date')),
                ('text', models.TextField(db_column='text')),
                ('link', models.TextField(db_column='link')),
                ('reference', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), db_column='reference', size=None)),
                ('md5', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), db_column='md5', size=None)),
                ('sha1', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), db_column='sha1', size=None)),
                ('sha256', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), db_column='sha256', size=None)),
                ('mail', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), db_column='mail', size=None)),
                ('ip', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), db_column='ip', size=None)),
                ('domain', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), db_column='domain', size=None)),
                ('url', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), db_column='url', size=None)),
                ('mentions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), db_column='mentions', size=None)),
                ('hashtags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), db_column='hashtags', size=None)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), db_column='images', size=None)),
            ],
            options={
                'db_table': 'tweets',
                'managed': True,
            },
        ),
    ]
