# Generated by Django 3.2.6 on 2022-01-26 19:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tweet'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterProfile',
            fields=[
                ('id', models.BigIntegerField(db_column='_id', primary_key=True, serialize=False)),
                ('username', models.TextField(db_column='username')),
                ('photo', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), db_column='photo', size=None)),
                ('date', models.DateTimeField(db_column='date')),
            ],
            options={
                'db_table': 'researcher',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='dashboard',
            name='totalcount',
            field=models.BigIntegerField(db_column='totalcount', null=True),
        ),
    ]
