# Generated by Django 3.2.6 on 2022-01-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribute',
            name='message_type',
            field=models.CharField(default='never', max_length=100),
        ),
    ]
