# Generated by Django 3.2.6 on 2022-01-26 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_alter_contribute_message_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribute',
            name='date',
        ),
    ]
