# Generated by Django 3.2.6 on 2022-01-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_remove_contribute_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribute',
            name='message_type',
            field=models.CharField(choices=[('user', 'New User'), ('falsepositive', 'False Positive Data'), ('module', 'New Module'), ('other', 'Other')], max_length=100),
        ),
    ]
